on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      contents: read   # required for private repo

    strategy:
      matrix:
        package: [sdk, cli, src]

    steps:
    - uses: ./.github/workflows/test.yml

    - name: Pack (release)
      run: |
        cd ./${{ matrix.package }}
        dotnet pack  -c Release -p:ContinuousIntegrationBuild=true
        cd ..

    ################################
    #  NUGET
    - name: Trusted Publishing (id-token permission required)
      uses: NuGet/login@v1
      id: login  # --> ${{ steps.login.outputs.NUGET_API_KEY }}
      with:
        user: ${{ secrets.NUGET_LOGIN }}

    - name: NuGet Publish
      run: |
        cd ./${{ matrix.package }}
        dotnet nuget push "bin/Release/*.nupkg"  \
          -k ${{ steps.login.outputs.NUGET_API_KEY }}  \
          -s https://api.nuget.org/v3/index.json \
          --timeout 60
        cd ..
