on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      contents: read   # required for private repo

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cli-unity: ["", "--unity"]
        cli-merge: ["", "--merge"]
        package: [sdk, cli, src]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x

    - name: Test (release)
      run: |
        dotnet clean          cli
        dotnet run  --project cli -c Release -- build \
          ${{ matrix.cli-unity }} \
          ${{ matrix.cli-merge }} \
          --force --output  ./.z__merged_dll__ \
          "./sample/*.cs"  # enquote to prevent expanding

        dotnet clean         sample/SampleConsumer
        dotnet run --project sample/SampleConsumer  -c Release

    - name: Pack (release)
      run: |
        ##dotnet build -c Release -p:ContinuousIntegrationBuild=true

        cd ./${{ matrix.package }}
        dotnet pack  -c Release -p:ContinuousIntegrationBuild=true
        cd ..

    ################################
    #  NUGET
    - name: Trusted Publishing (id-token permission required)
      uses: NuGet/login@v1
      id: login  # --> ${{ steps.login.outputs.NUGET_API_KEY }}
      with:
        user: ${{ secrets.NUGET_LOGIN }}

    - name: NuGet Publish
      run: |
        cd ./${{ matrix.package }}
        dotnet nuget push "bin/Release/*.nupkg"  \
          -k ${{ steps.login.outputs.NUGET_API_KEY }}  \
          -s https://api.nuget.org/v3/index.json \
          --timeout 60
        cd ..
