on:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity: ["", "--unity"]
        merge: ["", "--merge"]
        debug: ["", "--debug"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x

    - name: Test (release)
      run: |
        dotnet clean          cli
        dotnet run  --project cli -c Release -- build \
          ${{ matrix.unity }} \
          ${{ matrix.merge }} \
          ${{ matrix.debug }} \
          --force --output  ./.z__merged_dll__ \
          "./sample/*.cs"  # enquote to prevent expanding

        dnx -y FGenerator.Cli -- build \
          "test/*.cs" -f -o ./.z__merged_dll__

        dotnet clean         sample/SampleConsumer
        dotnet run --project sample/SampleConsumer  -c Release \
          -p:EmitCompilerGeneratedFiles=true \
          -p:CompilerGeneratedFilesOutputPath="../../.generated"

    - name: Pathfinder
      run:
        ls -al

    - name: Artifact
      if: ${{ !matrix.unity && !matrix.merge && !matrix.debug }}
      uses: actions/upload-artifact@v4
      with:
        name: generated-sources
        path: ./.generated/**
        include-hidden-files: true
