name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity: ["--unity", ""]
        merge: ["", "--merge"]
        debug: ["", "--debug"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x

    - name: Test (release)
      run: |
        dotnet run  --project cli -c Release -- build \
          ${{ matrix.unity }} \
          ${{ matrix.merge }} \
          ${{ matrix.debug }} \
          --force --output  ./.z__merged_dll__ \
          "FinalEnumGenerator/*.cs" "EnvObfuscator/*.cs" "sample/*.cs"  # enquote to prevent expanding

        dnx -y FGenerator.Cli -- build \
          ${{ matrix.unity }} \
          ${{ matrix.merge }} \
          ${{ matrix.debug }} \
          "test/*.cs" -f -o ./.z__merged_dll__

        dnx -y FGenerator.Cli -- build \
          ${{ matrix.unity }} \
          ${{ matrix.merge }} \
          ${{ matrix.debug }} \
          "Unity/*.cs" -f -o ./.z__merged_dll__

        ### Tests ###

        dotnet build         EnvObfuscator.Test  -c Release
        dotnet run --project EnvObfuscator.Test  -c Release  --no-build --verbosity quiet -p:WarningLevel=0 \
          -p:EmitCompilerGeneratedFiles=true \
          -p:CompilerGeneratedFilesOutputPath="../.generated" \
          --markdown >> $GITHUB_STEP_SUMMARY

        dotnet build         FinalEnumGenerator.Test  -c Release
        dotnet run --project FinalEnumGenerator.Test  -c Release  --no-build --verbosity quiet -p:WarningLevel=0 \
          -p:EmitCompilerGeneratedFiles=true \
          -p:CompilerGeneratedFilesOutputPath="../.generated" \
          --markdown >> $GITHUB_STEP_SUMMARY

        dotnet build         sandbox  -c Release
        dotnet run --project sandbox  -c Release  --no-build --verbosity quiet -p:WarningLevel=0 \
          -p:EmitCompilerGeneratedFiles=true \
          -p:CompilerGeneratedFilesOutputPath="../.generated" \
          --markdown >> $GITHUB_STEP_SUMMARY

    - name: Pathfinder
      run:
        ls -al

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-sources${{ matrix.unity }}${{ matrix.merge }}${{ matrix.debug }}
        path: ./.generated/**
        include-hidden-files: true
